networks:
  1panel-network:
    external: true
services:
  slink:
    container_name: slink
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - USER_PASSWORD_MIN_LENGTH=8
    - USER_PASSWORD_REQUIREMENTS=15
    - IMAGE_MAX_SIZE=15M
    - STORAGE_PROVIDER=local
    image: anirdev/slink:v1.4.9
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3000
    restart: always
    volumes:
    - ${SLINK_ROOT_PATH}/data:/app/var/data
    - ${SLINK_ROOT_PATH}/images:/app/slink/images
