networks:
  1panel-network:
    external: true
services:
  astrbot:
    container_name: astrbot
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: soulter/astrbot:v4.5.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:6185
    - ${PANEL_APP_PORT_QQ_WH}:6199
    - ${PANEL_APP_PORT_QQ_API}:6196
    - ${PANEL_APP_PORT_WECOM}:6195
    - ${PANEL_APP_PORT_WECHAT}:11451
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${ASTRBOT_ROOT_PATH}/data:/AstrBot/data
