networks:
  1panel-network:
    external: true
services:
  redis:
    command: "sh -c ' if [ -z \"${REDIS_ROOT_PASSWORD}\" ]; then\n  redis-server /etc/redis/redis.conf\n\
      else\n  redis-server /etc/redis/redis.conf --requirepass ${REDIS_ROOT_PASSWORD}\n\
      fi'\n"
    container_name: redis
    image: redis:6.2.18-alpine
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:6379
    restart: always
    volumes:
    - ${REDIS_ROOT_PATH}/data:/data
    - ${REDIS_ROOT_PATH}/config/redis.conf:/etc/redis/redis.conf
    - ${REDIS_ROOT_PATH}/logs:/logs
