networks:
  1panel-network:
    external: true

services:
  movie-pilot:
    image: jxxghp/moviepilot:2.8.0
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    stdin_open: true
    tty: true
    network_mode: ${NETWORK_MODE}
    ports:
      - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
      - ${PANEL_APP_PORT_API}:${PANEL_APP_PORT_API}
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${MOVIEPILOT_ROOT_PATH}/config:/config
      - ${MOVIEPILOT_ROOT_PATH}/moviepilot:/moviepilot
      - ${MOVIEPILOT_ROOT_PATH}/download:/download
      - ${CUSTOM_MOUNT_DIRECTORY_1:-./default_mount_1}:${CUSTOM_MOUNT_DIRECTORY_1:-/default_mount_1}
      - ${CUSTOM_MOUNT_DIRECTORY_2:-./default_mount_2}:${CUSTOM_MOUNT_DIRECTORY_2:-/default_mount_2}
      - ${CUSTOM_MOUNT_DIRECTORY_3:-./default_mount_3}:${CUSTOM_MOUNT_DIRECTORY_3:-/default_mount_3}
    environment:
      - NGINX_PORT=${PANEL_APP_PORT_HTTP}
      - PORT=${PANEL_APP_PORT_API}
      - DEBUG=false
      - DEV=false
      - LOG_LEVEL=INFO
    logging:
      driver: json-file
      options:
        max-size: 5m
