networks:
  1panel-network:
    external: true
services:
  beszel-agent:
    container_name: beszel-agent
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - LOG_LEVEL=info
    - PORT=${PANEL_APP_PORT_HTTP:-45876}
    image: henrygd/beszel-agent:0.11.1
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE:-host}
    ports:
    - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
