networks:
  1panel-network:
    external: true
services:
  onedev:
    container_name: onedev
    env_file:
    - ./envs/global.env
    - ./envs/onedev.env
    - .env
    environment:
    - initial_user=${INITIAL_USER}
    - initial_password=${INITIAL_PASSWORD}
    - initial_email=${INITIAL_EMAIL}
    - initial_server_url=${INITIAL_SERVER_URL}
    - initial_ssh_root_url=${INITIAL_SSH_ROOT_URL}
    image: 1dev/server:11.11.4
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:6610
    - ${PANEL_APP_PORT_SSH}:6611
    restart: always
    volumes:
    - ${ONEDEV_ROOT_PATH}/data:/opt/onedev
    - /var/run/docker.sock:/var/run/docker.sock
