networks:
  1panel-network:
    external: true
services:
  fider:
    container_name: fider
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}?sslmode=disable
    image: getfider/fider:v0.25.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3000
    restart: always
