networks:
  1panel-network:
    external: true
services:
  speedtest-tracker:
    container_name: speedtest-tracker-sqlite
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Asia/Shanghai
    - DISPLAY_TIMEZONE=Asia/Shanghai
    - DB_CONNECTION=sqlite
    - MAIL_MAILER=sqlite
    image: linuxserver/speedtest-tracker:1.4.0
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE}
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    restart: always
    volumes:
    - ${SPEEDTEST_TRACKER_ROOT_PATH}/config:/config
