networks:
  1panel-network:
    external: true

services:
  app_name:
    image: sn0wl1n/ech0:v2.9.5
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:6277
      - ${PANEL_APP_PORT_API}:6278
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${ECH0_ROOT_PATH}/data:/app/data
      - ${ECH0_ROOT_PATH}/backup:/app/backup
    environment:
      - TZ=Asia/Shanghai
      - HTTPS_PROXY=${HTTP_PROXY}
