networks:
  1panel-network:
    external: true
services:
  nodebb:
    container_name: nodebb
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    image: ghcr.io/nodebb/nodebb:4.3.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:4567
    restart: always
    volumes:
    - ${NODEBB_ROOT_PATH}/node_modules:/usr/src/app/node_modules
    - ${NODEBB_ROOT_PATH}/build:/usr/src/app/build
    - ${NODEBB_ROOT_PATH}/uploads:/usr/src/app/public/uploads
    - ${NODEBB_ROOT_PATH}/config:/opt/config
    - ${NODEBB_ROOT_PATH}/setup.json:/usr/src/app/setup.json
