networks:
  1panel-network:
    external: true
services:
  mdc-ng:
    container_name: mdc-ng
    env_file:
    - ./envs/global.env
    - .env
    image: mdcng/mdc:1.3.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:9208
    restart: always
    volumes:
    - ${MDC_NG_ROOT_PATH}/config:/config
    - ${MDC_NG_ROOT_PATH}/media:/media
    - ${CUSTOM_MOUNT_DIRECTORY_1:-./default_mount_1}:${CUSTOM_MOUNT_DIRECTORY_1:-/default_mount_1}
    - ${CUSTOM_MOUNT_DIRECTORY_2:-./default_mount_2}:${CUSTOM_MOUNT_DIRECTORY_2:-/default_mount_2}
    - ${CUSTOM_MOUNT_DIRECTORY_3:-./default_mount_3}:${CUSTOM_MOUNT_DIRECTORY_3:-/default_mount_3}
