networks:
  1panel-network:
    external: true
services:
  smtp_proxy_server:
    container_name: smtp-proxy-server
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - proxy_url=${PROXY_URL}
    - port=${PANEL_APP_PORT_SMTP}
    - imap_port=${PANEL_APP_PORT_IMAP}
    image: ghcr.io/dreamhunter2333/cloudflare_temp_email/smtp_proxy_server:v1.0.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_SMTP}:${PANEL_APP_PORT_SMTP}
    - ${PANEL_APP_PORT_IMAP}:${PANEL_APP_PORT_IMAP}
    restart: always
