networks:
  1panel-network:
    external: true
services:
  homarr:
    container_name: homarr
    env_file:
    - ./envs/global.env
    - .env
    image: ghcr.io/homarr-labs/homarr:v1.43.1
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE}
    ports:
    - ${PANEL_APP_PORT_HTTP}:7575
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${HOMARR_ROOT_PATH}/appdata:/appdata
