networks:
  1panel-network:
    external: true
services:
  dashdot:
    container_name: dashdot
    env_file:
    - ./envs/global.env
    - .env
    image: mauricenino/dashdot:5.9.2
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3001
    privileged: true
    restart: always
    volumes:
    - /:/mnt/host:ro
