networks:
  1panel-network:
    external: true
services:
  open-webui:
    container_name: open-webui
    devices:
    - /dev/dri:/dev/dri
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - PORT=8080
    - ENABLE_OLLAMA_API=True
    - ENABLE_OPENAI_API=False
    - https_proxy=${http_proxy}
    image: ghcr.io/open-webui/open-webui:v0.6.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8080
    restart: always
    volumes:
    - ${OPEN_WEBUI_ROOT_PATH}/data:/app/backend/data
