networks:
  1panel-network:
    external: true
services:
  synapse:
    container_name: synapse
    depends_on:
    - synapse-init
    env_file:
    - ./envs/global.env
    - .env
    image: matrixdotorg/synapse:v1.133.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8008
    restart: always
    volumes:
    - ${SYNAPSE_ROOT_PATH}/data:/data
  synapse-init:
    container_name: init-synapse
    entrypoint:
    - /start.py
    - generate
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - SYNAPSE_REPORT_STATS=no
    - SYNAPSE_NO_TLS=true
    - SYNAPSE_HTTP_PORT=8008
    image: matrixdotorg/synapse:v1.133.0
    networks:
    - 1panel-network
    restart: false
    volumes:
    - ${SYNAPSE_ROOT_PATH}/data:/data
