networks:
  1panel-network:
    external: true
services:
  kibana:
    container_name: elastic-kibana
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - SERVER_NAME="kibana"
    - SERVER_HOST="0.0.0.0"
    - SERVER_PORT=5601
    - I18N_LOCALE="zh-CN"
    - SERVER_SHUTDOWNTIMEOUT="5s"
    - MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true
    image: kibana:9.0.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:5601
    restart: always
    volumes:
    - ${KIBANA_ROOT_PATH}/data:/usr/share/kibana/data
