networks:
  1panel-network:
    external: true
services:
  dpanel:
    container_name: dpanel-lite
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - APP_NAME=${CONTAINER_NAME}
    - HTTPS_PROXY=${HTTP_PROXY}
    image: dpanel/dpanel:1.7.0-lite
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8080
    restart: always
    volumes:
    - ${DPANEL_ROOT_PATH}/data:/dpanel
    - ${DPANEL_ROOT_PATH}/compose:/dpanel/compose
    - /var/run/docker.sock:/var/run/docker.sock
