networks:
  1panel-network:
    external: true
services:
  sp-webdav:
    env_file:
    - ./envs/global.env
    - .env
    image: hacdias/webdav:latest
    networks:
    - 1panel-network
    restart: always
    volumes:
    - ${SUPER_PRODUCTIVITY_ROOT_PATH}/config/webdav.yaml:/config.yml
    - ${SUPER_PRODUCTIVITY_ROOT_PATH}/data:/data
  super-productivity:
    container_name: super-productivity
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - WEBDAV_BACKEND=http://sp-webdav
    image: johannesjo/super-productivity:v13.0.9
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    restart: always
