networks:
  1panel-network:
    external: true
services:
  jproxy:
    container_name: jproxy
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - PUID=0
    - PGID=0
    - TZ=Asia/Shanghai
    image: luckypuppy514/jproxy:v3.4.6
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8117
    restart: always
    volumes:
    - ${JPROXY_ROOT_PATH}/data:/app/database
