name: immich-server
networks:
  1panel-network:
    external: true
services:
  immich-server:
    container_name: immich-server-immich-server
    devices:
    - /dev/dri:/dev/dri
    env_file:
    - ./envs/global.env
    - .env
    image: ghcr.io/immich-app/immich-server:v1.134.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:2283
    restart: always
    volumes:
    - ${IMMICH_ROOT_PATH}/data/library:/usr/src/app/upload
    - /etc/localtime:/etc/localtime
