networks:
  1panel-network:
    external: true
services:
  sonarr:
    container_name: sonarr
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - PUID=1000
    - PGID=1000
    - UMASK=022
    - TZ=Asia/Shanghai
    image: linuxserver/sonarr:4.0.14
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:8989
    restart: always
    volumes:
    - ${SONARR_ROOT_PATH}/config:/config
    - ${SONARR_ROOT_PATH}/tv:/tv
    - ${SONARR_ROOT_PATH}/downloads:/downloads
    - ${CUSTOM_MOUNT_DIRECTORY_1:-./default_mount_1}:${CUSTOM_MOUNT_DIRECTORY_1:-/default_mount_1}
    - ${CUSTOM_MOUNT_DIRECTORY_2:-./default_mount_2}:${CUSTOM_MOUNT_DIRECTORY_2:-/default_mount_2}
    - ${CUSTOM_MOUNT_DIRECTORY_3:-./default_mount_3}:${CUSTOM_MOUNT_DIRECTORY_3:-/default_mount_3}
