networks:
  1panel-network:
    external: true
services:
  auto-lady:
    container_name: byte-muse
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - HTTPS_PROXY=${HTTP_PROXY}
    - HTTP_PROXY=${HTTP_PROXY:-}
    - NO_PROXY=${NO_PROXY:-}
    image: envyafish/byte-muse:1.11.2
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:80
    restart: always
    volumes:
    - ${AUTO_LADY_ROOT_PATH}/config:/data
    - ${CUSTOM_MOUNT_DIRECTORY_1:-./default_mount_1}:${CUSTOM_MOUNT_DIRECTORY_1:-/default_mount_1}
    - ${CUSTOM_MOUNT_DIRECTORY_2:-./default_mount_2}:${CUSTOM_MOUNT_DIRECTORY_2:-/default_mount_2}
    - ${CUSTOM_MOUNT_DIRECTORY_3:-./default_mount_3}:${CUSTOM_MOUNT_DIRECTORY_3:-/default_mount_3}
