name: immich
networks:
  1panel-network:
    external: true
services:
  immich-machine-learning:
    container_name: immich-machine-learning-immich
    devices: &id001
    - /dev/dri:/dev/dri
    env_file:
    - ./envs/global.env
    - .env
    image: ghcr.io/immich-app/immich-machine-learning:v1.135.2
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_MACHINE_LEARNING}:3003
    restart: always
    volumes:
    - ${IMMICH_ROOT_PATH}/data/cache:/cache
  immich-pg14-vectors:
    container_name: pg14-vectors-immich
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME:-immich}
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.1-pgvectors0.2.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_DB:-5432}:5432
    restart: always
    volumes:
    - ${IMMICH_ROOT_PATH}/pg14/data:/var/lib/postgresql/data
  immich-server:
    container_name: immich-server-immich
    depends_on:
    - immich-pg14-vectors
    devices: *id001
    env_file:
    - ./envs/global.env
    - .env
    image: ghcr.io/immich-app/immich-server:v1.135.2
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:2283
    restart: always
    volumes:
    - ${IMMICH_ROOT_PATH}/data/library:/usr/src/app/upload
    - /etc/localtime:/etc/localtime
