networks:
  1panel-network:
    external: true
services:
  nodepassdash:
    container_name: nodepassdash
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - PORT=${PANEL_APP_PORT_HTTP}
    image: ghcr.io/nodepassproject/nodepassdash:2.1.3
    labels:
      createdBy: Apps
    network_mode: ${NETWORK_MODE}
    ports:
    - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    restart: always
    volumes:
    - ${NODEPASSDASH_ROOT_PATH}/logs:/app/logs
    - ${NODEPASSDASH_ROOT_PATH}/public:/app/public
