networks:
  1panel-network:
    external: true
services:
  alist:
    container_name: alist
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - PUID=0
    - PGID=0
    - UMASK=022
    - FORCE=false
    image: xhofe/alist:v3.44.0
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:5244
    restart: always
    volumes:
    - ${ALIST_ROOT_PATH}/data:/opt/alist/data
    - ${CUSTOM_MOUNT_DIRECTORY_1:-./default_mount_1}:${CUSTOM_MOUNT_DIRECTORY_1:-/default_mount_1}
    - ${CUSTOM_MOUNT_DIRECTORY_2:-./default_mount_2}:${CUSTOM_MOUNT_DIRECTORY_2:-/default_mount_2}
    - ${CUSTOM_MOUNT_DIRECTORY_3:-./default_mount_3}:${CUSTOM_MOUNT_DIRECTORY_3:-/default_mount_3}
