networks:
  1panel-network:
    external: true
services:
  ghost:
    container_name: ghost
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - NODE_ENV=production
    - server__host=0.0.0.0
    - server__port=2368
    - database__client=mysql
    - mail__options__service=Email
    - mail__options__secure=true
    image: ghost:5.129.1
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:2368
    restart: always
    volumes:
    - ${GHOST_ROOT_PATH}/data:/var/lib/ghost/content
