networks:
  1panel-network:
    external: true
services:
  minio:
    command: server --console-address :${PANEL_APP_PORT_HTTP} --address :${MINIO_API_PORT}
      --json
    container_name: minio
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - MINIO_VOLUMES=/data
    - MINIO_API_ROOT_ACCESS=on
    - MINIO_BROWSER_REDIRECT=true
    extra_hosts:
    - ${MINIO_SERVER_HOST:-localhost}:127.0.0.1
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    labels:
      createdBy: Apps
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 5M
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}
    - ${PANEL_APP_PORT_API}:${MINIO_API_PORT}
    restart: always
    volumes:
    - ${MINIO_ROOT_PATH}/certs:/root/.minio/certs
    - ${MINIO_ROOT_PATH}/data:/data
