networks:
  1panel-network:
    external: true

services:
  kspeeder:
    image: linkease/kspeeder:0.3.3
    container_name: ${CONTAINER_NAME}
    labels:
      createdBy: "Apps"
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:5003
      - ${PANEL_APP_PORT_API}:5443
    env_file:
      - ${GLOBAL_ENV_FILE:-/etc/1panel/envs/global.env}
      - ${ENV_FILE:-/etc/1panel/envs/default.env}
    volumes:
      - ${KSPEEDER_ROOT_PATH}/data:/kspeeder-data
      - ${KSPEEDER_ROOT_PATH}/config:/kspeeder-config
    environment:
      - TZ=Asia/Shanghai
