networks:
  1panel-network:
    external: true
services:
  mysql:
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --mysql-native-password=ON
    container_name: mysql
    env_file:
    - ./envs/global.env
    - .env
    image: mysql:8.4.5
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3306
    restart: always
    user: 1000:1000
    volumes:
    - ${MYSQL_ROOT_PATH}/data:/var/lib/mysql
    - ${MYSQL_ROOT_PATH}/config/my.cnf:/etc/my.cnf
    - ${MYSQL_ROOT_PATH}/log:/var/log/mysql
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
