networks:
  1panel-network:
    external: true
services:
  page-spy-web:
    container_name: page-spy-web
    env_file:
    - ./envs/global.env
    - .env
    image: huolalatech/page-spy-web:v2.3.3
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:6752
    restart: always
    volumes:
    - ${PAGE_SPY_WEB_ROOT_PATH}/log:/app/log
    - ${PAGE_SPY_WEB_ROOT_PATH}/data:/app/data
