networks:
  1panel-network:
    external: true
services:
  app_name:
    container_name: ech0
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - HTTPS_PROXY=${HTTP_PROXY}
    image: sn0wl1n/ech0:v2.9.5
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:6277
    - ${PANEL_APP_PORT_API}:6278
    restart: always
    volumes:
    - ${ECH0_ROOT_PATH}/data:/app/data
    - ${ECH0_ROOT_PATH}/backup:/app/backup
